FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu16.04

RUN apt-get update -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update -y
RUN apt-get install python3.7 -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 0
RUN apt-get install python3-pip -y
RUN apt-get install redis-server -y 
RUN pip3 install --upgrade setuptools pip
RUN apt-get install libsm6 libxext6 libxrender1 libglib2.0-0 ffmpeg -y
