FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu16.04

RUN apt-get update -y
RUN apt-get install redis-server -y 
RUN apt-get install python3 -y 
RUN apt-get install python3-pip -y
RUN pip3 install --upgrade setuptools pip
RUN pip3 install --upgrade pip
